### ISSUE TITLE
Adding to awesome-diarization repo

### ISSUE THREAD

**Issue by judyfong** [cadia-lvl/diar-az#4]
@afk0901 can you add this to the awesome diarization repo by quan wang? Also I am writing a blogpost, interested in helping me with it finally?

**Comment by afk0901** [comment]
I made a pull request: https://github.com/wq2012/awesome-diarization/pull/39. Ah! The blogpost! Yes, I'm interested in helping you with that!

**Comment by judyfong** [comment]
Awesome then I guess we can close this issue once your PR has been merged
in. Also, perhaps you could reference that merge in our readme here.

**Comment by afk0901** [comment]
@judyfong Referenced the merge in the readme. https://github.com/cadia-lvl/diar-az/pull/6

**Comment by judyfong** [comment]
https://github.com/wq2012/awesome-diarization/pull/39

But you didb’t reference the pr itself
